### ISSUE TITLE
Update prometheus and ingress-nginx dependencies, multiple major versions behind

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/mybinder.org-deploy#2182]
With #2180 we now have automation to do regular dependency bumps of our charts. But, at this point, we are several major versions behind for prometheus and ingress-nginx.

I've outlined steps for how to upgrade these:

- ingress-nginx ([research notes here](https://github.com/jupyterhub/mybinder.org-deploy/pull/2203#issuecomment-1140237287)):
   - [x] upgrade the chart to 3.36.0 (appVersion: 0.49.0) (merge #2214)
   - [x] upgrade our Ingress resources from v1beta1 to v1 (merge #2224)
   - [ ] upgrade the chart to the latest version (merge #2203)
prometheus: https://github.com/jupyterhub/mybinder.org-deploy/pull/2201#issuecomment-1140235678

- prometheus:
  - [ ] Delete deployment resources that can't be helm upgraded, without deleting its owned replicasets and pods, for all deployments.
    ```shell
    # this command will delete the deployment resource, but not the replica-sets/pods it owns
    # instead, these pods will be orphaned, and can later be managed by the new deployment
    # to be created
    kubectl delete deploy -n <namespace here> -l app.kubernetes.io/instance=prometheus,app.kubernetes.io/name=kube-state-metrics --cascade=orphan
    ```
    - [ ] GKE Staging
    - [ ] GKE Prod
    - [ ] Turing
    - [ ] OVH
  - [ ] upgrade the chart to the latest version (merge #2201)

**Comment by consideRatio** [comment]
I've provided action points for these:

ingress-nginx: https://github.com/jupyterhub/mybinder.org-deploy/pull/2203#issuecomment-1140237287
prometheus: https://github.com/jupyterhub/mybinder.org-deploy/pull/2201#issuecomment-1140235678

Anyone wanting to help out, please go for it!

**Comment by minrk** [comment]
> upgrade our Ingress resources from v1beta1 to v1

I believe all of our ingresses are already v1. Is that not the case?

```
$ kubectl get ing -o yaml | grep apiVersion
apiVersion: v1
- apiVersion: networking.k8s.io/v1
- apiVersion: networking.k8s.io/v1
    - apiVersion: acme.cert-manager.io/v1alpha2
- apiVersion: networking.k8s.io/v1
- apiVersion: networking.k8s.io/v1
- apiVersion: networking.k8s.io/v1
- apiVersion: networking.k8s.io/v1
- apiVersion: networking.k8s.io/v1
```

**Comment by consideRatio** [comment]
Those directly part of the mybinder helm chart's templates are as of #2224 v1, but I bet there can be old resources generated by the use of old helm charts like prometheus.

So, lets bump prometheus helm chart at this point.

**Comment by minrk** [comment]
Yup, that's all our ingress resources from this whole chart. And #2203 succeeded on staging, so going ahead with that one
