### ISSUE TITLE
Checklist for verifying a deployment to staging

### ISSUE THREAD

**Issue by minrk** [jupyterhub/mybinder.org-deploy#263]
Action item from #261 incident report

cc @willingc 

Right now, we have [these instructions](https://github.com/jupyterhub/mybinder.org-deploy#deploying-a-change) for deploying, including what to do when a deploy fails.

What is missing is some information about what it *means* for a deploy to fail, and what the "Verify that staging.mybinder.org works as intended" step is. A checklist, as described in the #261 incident report, ought to help here.

Now that we have tests, Travis claiming a failure *should* mean that the deploy failed, but it does not necessarily, especially right now when we are having a high false-failure rate. This is a major issue, because untrustworthy tests cause problems (see #261), and should be addressed directly. #262 should be a mitigation for these, but not perfect.

Some notes on this:

a deploy (as in Travis is red) can fail in two ways:

1. the deploy *actually* fails because the config is bad, or something else went wrong and it genuinely doesn't work. Various pieces of Binder may not be running or working at this point.
2. the deploy completed, but tests failed, possibly because it didn't work, and possibly because the tests are wrong.

Travis being red is only an *indicator* of failure, it does not mean that deploy failed. Similarly, Travis being green is only an *indicator* of success, it does not mean that deploy succeeded. When Travis fails, the logs need to be inspected.

Travis does two things:

1. perform the actual deployment
2. run tests to validate it

Travis does *not* take any action based on the test results. In particular, if the deployment completed and the tests failed, the deployment is still in tact and can be inspected manually after the failure.

We have been re-running Travis manually recently due to some flaky tests (#262 automates the retry). We should clarify what re-running Travis means, as it is a common practice across projects when tests fail for various reasons and we don't trust the results:

1. the deployment will be re-run, but since the previous deployment is still in-tact this is a no-op
2. the tests will be re-run

We should encode that it is *okay* to restart Travis. Travis can also fail due to intermittent network issues during the installation process and other issues that don't mean our deployment needs reverting.

Until and unless we have vastly more test coverage, some manual inspection of the deployment is currently required, both for overriding Travis's conclusions (in both directions), and for verifying potentially untested functionality.

One step in the current instructions that I think is misleading is that the first step if the changes don't look correct is:

> Immediately revert the PR that was made to the staging branch.

I don't think this is correct, because staging is largely there for testing. It should be okay to inspect a failed deploy for a bit to try to figure out what went wrong. The deploy *should* be reverted, but it does not need to be immediate. This disgnosis process could be encoded in the "Verify that staging.mybinder.org works as intended" step, though. Add it to the checklist!

---

Proposed starting point for the checklist (amend as appropriate!):

- [ ] verify that deployed change has been uploaded. If you just merged a PR upstream, that usually means waiting for Travis to complete, https://travis-ci.org/jupyterhub/binderhub for the binder chart and https://travis-ci.org/jupyter/repo2docker for repo2docker. The binder chart will be listed [here](https://jupyterhub.github.io/helm-chart/#development-releases-binderhub) after upload is complete and the repo2docker image [here](https://hub.docker.com/r/jupyter/repo2docker/tags/).
- [ ] update versions. Most often, this is changing the binderhub version in mybinder/requirements.yaml and/or repo2docker version in mybinder/values.yaml.
- [ ] check Travis result

Travis green:

- [ ] if deployed change fixes a specific bug, e.g. a particular repo failed to build, try building that repo. If it's a UI change, try out that UI, etc.
- [ ] when you are satisfied that the deployment is successful, deploy to production.

Travis red:

- [ ] identify why Travis failed. Could be a failed deploy, failed tests, or intermittent issues with Travis itself or upstream issues (apt-get install can fail sometimes!)
- [ ] if the deploy completed and tests failed and the cause is inconclusive, try some manual diagnosis with the deployment. If all looks well, the test failure may have been incorrect.
- [ ] if test result is untrustworthy for some reason (e.g. tests have been flaky recently, looks like an upstream problem during installation, etc.), restart Travis to try the deploy again
- [ ] when diagnosis is complete (or you are giving up, which is fine!), revert the deployment. If you have a fix ready to go based on the diagnosis, it can be deployed right away instead of reverting.
- [ ] If a fix is unknown, open an Issue describing the failure to deploy the latest update.

**Comment by choldgraf** [comment]
Hey all - I think that some of these to-do items are outdated (e.g. we now have a single deploy step, not a two-step process as before), and some are already accomplished. Can we update this so that it's ready to go? (or can we close this and bring up subsequent issues as necessary?)
