### ISSUE TITLE
Adhere to the EFF's Do Not Track policy for allowing people to opt out of tracking

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/mybinder.org-deploy#825]
https://www.eff.org/dnt-policy

The remaining steps on this one are:

- [ ] Copy the text from the EFF DNT policy (https://github.com/EFForg/dnt-policy/blob/master/dnt-policy-1.0.txt) into the `mybinder.org-deploy` repo
- [ ] Confirm that we can copy the policy verbatim and still adhere to it
- [ ] Create a privacy section in `docs.mybinder.org` and link to the EFF text file in the deploy repo.

**Comment by manics** [comment]
Closing, we implemented this for Matomo, but we've since switched to Plausible, and since DNT is deprecated due to lack of support I don't think it's worth investing more time https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/DNT
